env:
  CIRRUS_CLONE_DEPTH: 1
  VT_TYPE: qemu

fedora_33_task:
  container:
    image: quay.io/avocado-framework/avocado-vt-ci-fedora-33
  env:
    PYTHON: python3
    matrix:
      # Get deps from setup.py (therefor pip version of avocado)
      - AVOCADO_SRC:
      # Latest LTS release is 69.x
      - AVOCADO_SRC: avocado-framework<70.0
      # Latest Avocado from git
      - AVOCADO_SRC: git+https://github.com/avocado-framework/avocado#egg=avocado_framework
    matrix:
      - SETUP: setup.py develop --user
      - SETUP: -m pip install .
      - SETUP: -m pip install PYPI_UPLOAD/*.whl
    matrix:
      - VT_TYPE: qemu
      - VT_TYPE: libvirt
  build_script:
    - (echo $SETUP | grep -v PYPI_UPLOAD) || make pypi
  setup_script: &setup_scr
    - $PYTHON --version
    - test -z $AVOCADO_SRC || $PYTHON -m pip install $AVOCADO_SRC
    - $PYTHON $SETUP
  bootstrap_script: &bootstrap_scr
    - $PYTHON -m avocado vt-bootstrap --vt-type=$VT_TYPE --vt-skip-verify-download-assets --yes-to-all
  list_script: &list_scr
    - $PYTHON -m avocado list --vt-type=$VT_TYPE
  dry_run_script: &dry_run_scr
    - $PYTHON -m avocado --show all run --vt-type=$VT_TYPE --dry-run -- io-github-autotest-qemu.boot

centos_8_1_task:
  container:
    image: quay.io/avocado-framework/avocado-vt-ci-centos-8.1
  env:
    PYTHON: python3
    matrix:
      - AVOCADO_SRC:
      - AVOCADO_SRC: avocado-framework<70.0
      - AVOCADO_SRC: git+https://github.com/avocado-framework/avocado#egg=avocado_framework
    matrix:
      - SETUP: setup.py develop --user
      - SETUP: -m pip install .
  setup_script:
    *setup_scr
  bootstrap_script:
    *bootstrap_scr
  list_script:
    *list_scr
  dry_run_script:
    *dry_run_scr

centos_7_task:
  env:
    PYTHON: python2
    matrix:
      - AVOCADO_SRC:
      - AVOCADO_SRC: avocado-framework<70.0
    matrix:
      - SETUP: setup.py develop --user
      - SETUP: -m pip install .
  container:
    image: quay.io/avocado-framework/avocado-vt-ci-centos-7
  setup_script:
    *setup_scr
  bootstrap_script:
    *bootstrap_scr
  list_script:
    *list_scr
  dry_run_script:
    *dry_run_scr
