#!/bin/bash
GR=0
run_rc() {
    echo "Running '$1'"
    $1
    if [ $? != 0 ]; then
        GR=1
    fi
    echo ""
}
run_rc 'inspekt --exclude=.git lint'
run_rc 'inspekt --exclude=.git indent'
run_rc 'inspekt --exclude=.git style --disable E501,E265,W503,W601,E402,E722'
run_rc 'selftests/run'
exit ${GR}

