#!/bin/bash
GR=0
run_rc() {
    echo "Running '$1'"
    $1
    if [ $? != 0 ]; then
        GR=1
    fi
    echo ""
}
run_rc 'inspekt lint --exclude=.git'
run_rc 'inspekt indent --exclude=.git'
run_rc 'inspekt style --exclude=.git --disable E501,E265,W503,W601,E402,E722'
run_rc 'selftests/run'
exit ${GR}

