#!/bin/bash

# number of infringements found
RESULT=0

echo -n "* Checking for non-relative avocado imports from avocado/core: "
LIST=`git grep -E '^(import avocado\..*|from avocado(.*)import)' avocado/core`
COUNT=`git grep -E '^(import avocado\..*|from avocado(.*)import)' avocado/core | wc -l`
(( RESULT = RESULT + COUNT ))
echo "$COUNT"
if [ -n "$LIST" ]; then
   echo "$LIST"
fi
unset LIST
unset COUNT

if [ "$RESULT" -ne 0 ]; then
    echo "ERROR: $RESULT module boundary infringements found"
else
    echo "PASS: no module boundary infringement(s) found"
fi
exit $RESULT
